### ISSUE TITLE
Cannot set profile picture on help.nextcloud.com

### ISSUE THREAD

**Issue by aptiko** [nextcloud/nextcloud.com#1614]
In my profile settings, I try to change my profile picture.

If I try Gravatar (based on my email address), it says "Sorry, we can't find any avatar associated with that email address". This is probably an error, as there *is* a gravatar. At the same time, the JavaScript console shows `PUT https://help.nextcloud.com/u/aptiko/preferences/avatar/pick 422`.

If I try to upload a custom picture, then the moment I select it the JavaScript console shows `Uncaught TypeError: e._perFileData is not a function`. It then stays in "Uploading... 0%" for ever.

I have exactly the same symptoms in Firefox and Chromium.

**Comment by ItsMeOnceMore** [comment]
Hi, same problem here.
Here are a few details I can add:
System: MacOS 10.15.7
Browsers: Safari, Firefox
Network connection: ethernet in the LAN, VPN on the machine.

**Comment by tryallthethings** [comment]
Similar issue for me. The default assigned avatar is not shown. When opening the image [](https://help.nextcloud.com/letter_avatar_proxy/v4/letter/t/e56c9b/45.png) I get an nginx error:
504 Gateway Time-out
nginx

When trying to upload a custom image (~230kb) it starts and reaches 100% relatively quickly but stalls afterwards. Then I just get 
![image](https://user-images.githubusercontent.com/11146296/173666987-1dcdf265-71bb-4035-adc8-75cc62a768a4.png)

Meanwhile the Chrome Developer console is flodded with errors:

```
20:43:54.472 Access to fetch at 'https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Light.woff' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
1720:50:27.000 The FetchEvent for "<URL>" resulted in a network error response: the promise was rejected.
20:43:54.473 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Light.woff"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:43:54.508 Access to fetch at 'https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Bold.woff' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:43:54.508 Access to fetch at 'https://nextcloud.com/wp-content/themes/nextcloud-theme/dist/fonts/OpenSansLight.ttf' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:43:54.508 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Bold.woff"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:43:54.508 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/nextcloud-theme/dist/fonts/OpenSansLight.ttf"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:43:54.615 Access to fetch at 'https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Regular.woff' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:43:54.616 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Regular.woff"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:43:54.656 Access to fetch at 'https://nextcloud.com/wp-content/themes/nextcloud-theme/dist/fonts/OpenSansRegular.ttf' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:43:54.657 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/nextcloud-theme/dist/fonts/OpenSansRegular.ttf"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:47:05.939 Access to fetch at 'https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Light.woff' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:47:05.939 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Light.woff"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:47:06.014 Access to fetch at 'https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Bold.woff' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:47:06.015 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Bold.woff"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:47:06.051 Access to fetch at 'https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Regular.woff' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:47:06.051 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Regular.woff"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:47:06.095 Access to fetch at 'https://nextcloud.com/wp-content/themes/nextcloud-theme/dist/fonts/OpenSansRegular.ttf' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:47:06.096 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/nextcloud-theme/dist/fonts/OpenSansRegular.ttf"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:47:09.626 Access to fetch at 'https://nextcloud.com/wp-content/themes/nextcloud-theme/dist/fonts/OpenSansLight.ttf' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:47:09.626 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/nextcloud-theme/dist/fonts/OpenSansLight.ttf"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:47:25.148 Access to fetch at 'https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Italic.woff' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:47:25.149 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Italic.woff"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:47:40.338 ​ Refused to load the script 'https://stats.nextcloud.com/piwik.js' because it violates the following Content Security Policy directive: "script-src https://help.nextcloud.com/logs/ https://help.nextcloud.com/sidekiq/ https://help.nextcloud.com/mini-profiler-resources/ https://help.nextcloud.com/assets/ https://help.nextcloud.com/brotli_asset/ https://help.nextcloud.com/extra-locales/ https://help.nextcloud.com/highlight-js/ https://help.nextcloud.com/javascripts/ https://help.nextcloud.com/plugins/ https://help.nextcloud.com/theme-javascripts/ https://help.nextcloud.com/svg-sprite/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

(anonymous) @ 896f1d8……2c9a1db3c15d4.js:11
20:47:41.159 application-08fe03a4146cd98cb1bf41d9933febef.js:4246 [PLUGIN discourse-legal-tools] To prevent errors in tests, add a `pluginId` key to your `modifyClass` call. This will ensure the modification is only applied once.
oe @ application-08fe03a4146cd98cb1bf41d9933febef.js:4246
20:47:41.387 /letter_avatar_proxy/v4/letter/a/6a8cbe/32.png:1          Failed to load resource: the server responded with a status of 500 ()
20:47:41.394 Access to fetch at 'https://nextcloud.com/wp-content/themes/nextcloud-theme/dist/fonts/OpenSansLight.ttf' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:47:41.394 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/nextcloud-theme/dist/fonts/OpenSansLight.ttf"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:47:41.394 Access to fetch at 'https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Bold.woff' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:47:41.394 OpenSansLight.ttf:1          Failed to load resource: net::ERR_FAILED
20:47:41.394 Access to fetch at 'https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Light.woff' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:47:41.395 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Bold.woff"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:47:41.395 OpenSans-Bold.woff:1          Failed to load resource: net::ERR_FAILED
20:47:41.395 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Light.woff"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:47:41.395 OpenSans-Light.woff:1          Failed to load resource: net::ERR_FAILED
20:47:41.505 Access to fetch at 'https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Regular.woff' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:47:41.505 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Regular.woff"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:47:41.505 OpenSans-Regular.woff:1          Failed to load resource: net::ERR_FAILED
20:47:41.540 Access to fetch at 'https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Italic.woff' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:47:41.541 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/next/assets/fonts/OpenSans-Italic.woff"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:47:41.541 OpenSans-Italic.woff:1          Failed to load resource: net::ERR_FAILED
20:47:41.554 Access to fetch at 'https://nextcloud.com/wp-content/themes/nextcloud-theme/dist/fonts/OpenSansRegular.ttf' from origin 'https://help.nextcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
20:47:41.555 workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://nextcloud.com/wp-content/themes/nextcloud-theme/dist/fonts/OpenSansRegular.ttf"}]
    at a.makeRequest (https://help.nextcloud.com/javascripts/workbox/workbox-strategies.prod.js:1:2145)
20:47:41.555 OpenSansRegular.ttf:1          Failed to load resource: net::ERR_FAILED
20:47:58.470 /letter_avatar_proxy/v4/letter/a/6a8cbe/20.png:1          Failed to load resource: the server responded with a status of 500 ()
20:48:43.230 /topics/timings:1          Failed to load resource: the server responded with a status of 504 ()
20:48:43.230 application-08fe03a4146cd98cb1bf41d9933febef.js:7328 Failed to update topic times for topic 133409 due to 504 error
(anonymous) @ application-08fe03a4146cd98cb1bf41d9933febef.js:7328
20:49:04.094 /letter_avatar_proxy/v4/letter/a/6a8cbe/45.png:1          Failed to load resource: the server responded with a status of 504 ()
20:49:42.502 120.png:1          Failed to load resource: the server responded with a status of 504 ()
20:49:46.476 45.png:1          Failed to load resource: the server responded with a status of 504 ()
20:50:53.328 chunk.529.aa725730e4ff5434410f-56e62364f1d6680c43582809ddc21262.js:734 [Uppy] [20:50:53] Failed to upload roots_small.jpg Upload stalled for 30 seconds, aborting.
error @ chunk.529.aa725730e4ff5434410f-56e62364f1d6680c43582809ddc21262.js:734
value @ chunk.529.aa725730e4ff5434410f-56e62364f1d6680c43582809ddc21262.js:675
Q @ chunk.529.aa725730e4ff5434410f-56e62364f1d6680c43582809ddc21262.js:691
(anonymous) @ chunk.529.aa725730e4ff5434410f-56e62364f1d6680c43582809ddc21262.js:706
(anonymous) @ chunk.529.aa725730e4ff5434410f-56e62364f1d6680c43582809ddc21262.js:1621
e.emit @ chunk.529.aa725730e4ff5434410f-56e62364f1d6680c43582809ddc21262.js:1621
value @ chunk.529.aa725730e4ff5434410f-56e62364f1d6680c43582809ddc21262.js:610
(anonymous) @ chunk.529.aa725730e4ff5434410f-56e62364f1d6680c43582809ddc21262.js:975
```

**Comment by aptiko** [comment]
A few days ago I tried again and this time setting my profile picture with Gravatar worked. I haven't tried the uploading option.
